name: GitHub Snake Game

on:
  schedule:
    - cron: '0 0 * * *'          # every day at 00:00 UTC
  workflow_dispatch:              # manual run button
  push:
    branches: [main]              # run when you push to main

# 👇 give the default GITHUB_TOKEN write access so the deploy step can push
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1) Checkout full history (snk sometimes needs >1 commit)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0          # <-- grabs full git history

      # 2) Build the snake assets
      - name: Generate GitHub-contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: mohibatif        # <- your username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3) Push /dist to the `output` branch
      - name: Deploy snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: output
          commit_message: "chore: update snake animation [skip ci]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
